trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot/'
  dotnetSdkVersion: '6.x'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK $(dotnetSdkVersion)'
    inputs:
      packageType: 'sdk'
      version: '$(dotnetSdkVersion)'
    # Use .NET SDK

  - task: Npm@1
    displayName: 'Run npm install'  # Correct placement of displayName
    inputs:
      verbose: false
    # Run npm install

  - script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
    displayName: 'Compile node-sass'
    # Compile node-sass

  - task: gulp@1
    displayName: 'Run gulp tasks'
    # Run gulp tasks

  - task: DotNetCoreCLI@2
    displayName: 'Restore project dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
    # Restore project dependencies

  - task: DotNetCoreCLI@2
    displayName: 'Build the project - $(buildConfiguration)'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--no-restore --configuration $(buildConfiguration)'
    # Build the project

  - script: 'echo $"(Build.SourcesDirectory), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
    displayName: 'Write build information to file'
    workingDirectory: Tailspin.SpaceGame.Web/wwwroot/
    # Write build information to file

  - task: DotNetCoreCLI@2
    displayName: 'Publish the project - $(buildConfiguration)'
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      publishWebProjects: false
      arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    condition: succeeded()